spring:
  datasource:
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost/javatest
    userName : andersen
    password : andersen

  jpa:
    hibernate:
      ddl-auto : update
